Don't interpolate unicode into str in trim_filename().
Causes the following crash:

          File "/vagrant/src/inbox/server/models/message.py", line 22, in trim_filename
    "characters. {1}".format(max_len, s))
        UnicodeEncodeError: 'ascii' codec can't encode character u'\u2014' in position 44: ordinal not in range(128)