Remove redundant namespace filter in thread_query_api().
`g.filter` gets the namespace id on instantiation, and already filters by it in
`g.filter.thread_query`. Since this also applies a limit and offset, calling
`Query.filter()` again in `thread_query_api` causes the error:

InvalidRequestError: Query.filter() being called on a Query which already has
LIMIT or OFFSET applied. To modify the row-limited results of a Query, call
from_self() first. Otherwise, call filter() before limit() or offset() are
applied.