Don't ship with editable (-e) repos in requirements.txt
pip clones such repos into src/, and it prompts you if you try to change the
location of the remote:

    Obtaining zerorpc from git+https://github.com/inboxapp/zerorpc-python.git@master#egg=zerorpc (from -r requirements.txt (line 21))
      git clone in ./src/zerorpc exists with URL git://github.com/inboxapp/zerorpc-python.git
      The plan is to install the git repository https://github.com/inboxapp/zerorpc-python.git
    What to do?  (s)witch, (i)gnore, (w)ipe, (b)ackup Your response ('exit') was not one of the expected responses: s, i, w, b
    What to do?  (s)witch, (i)gnore, (w)ipe, (b)ackup Exception:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 126, in main
        self.run(options, args)
      File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 223, in run
        requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
      File "/usr/lib/python2.7/dist-packages/pip/req.py", line 930, in prepare_files
        req_to_install.update_editable(not self.is_download)
      File "/usr/lib/python2.7/dist-packages/pip/req.py", line 378, in update_editable
        vcs_backend.obtain(self.source_dir)
      File "/usr/lib/python2.7/dist-packages/pip/vcs/git.py", line 105, in obtain
        if self.check_destination(dest, url, rev_options, rev_display):
      File "/usr/lib/python2.7/dist-packages/pip/vcs/__init__.py", line 204, in check_destination
        response = ask('What to do?  %s' % prompt[0], prompt[1])
      File "/usr/lib/python2.7/dist-packages/pip/util.py", line 103, in ask
        response = raw_input(message)
    EOFError: EOF when reading a line

The git repos in src/ also don't get cleaned by git-clean, which is
slightly annoying.